# Puerto donde correra la API web de Spring Boot
server.port=8080

# Ruta al archivo de credenciales de Firebase
# para la llave de servicio, se asume que el archivo se encuentra en "src/main/resources/firebase-key.json"
firebase.credenciales.ruta=classpath:firebase-key.json

# Ubicamos las vistas HTML dentro de la carpeta "Vistas" en "resources"
spring.web.resources.static-locations=classpath:/Vistas/

#configuración de la conexion a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Brazo_Robot
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver